### ISSUE TITLE
Solidify Project Topic

### ISSUE THREAD

**Issue by MBickler** [CSIS-BU/cis445-project1-team1000#1]
As for right now, we know that our topic will be comparing **Python** and **C++**. Both of these languages are extremely relevant in multiple sectors of the technology/software field. With our initial direction, I suggest we focus on perhaps two or three jobs that utilize these two languages and expand our research from there.

**Comment by djlin** [comment]
Good. Maybe find something relevant to your other projects/courses. For example, if you are taking the security class, you may compare the implementation of different algorithms and their performance in both C++ and Python. Just my 0.02. But you are free to select something of your interest.

**Comment by MBickler** [comment]
In light of what Professor Lin said, another direction we could take with our research could be Computer Information Systems development. Just a suggestion.

**Comment by MBickler** [comment]
After some brief discussion, our project will focus entirely the two languages of *Python* and *C++*, and their *performance associated with cryptographic algorithms*.
